# Generated by Django 4.0.2 on 2022-04-16 22:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Approvals',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('married', models.CharField(choices=[('Married', 'Married'), ('Not married', 'No')], max_length=15)),
                ('dependents', models.IntegerField(default=0)),
                ('education', models.CharField(choices=[('Post Secondary', 'not graduate'), ('Post Graduate', 'graduate')], max_length=15)),
                ('self_employed', models.CharField(choices=[('Yes', 'yes'), ('No', 'no')], max_length=15)),
                ('applicant_income', models.FloatField(default=0)),
                ('coapplicant_income', models.FloatField(default=0)),
                ('loan_amount', models.FloatField(default=0)),
                ('loan_amount_term', models.FloatField(default=0)),
                ('credit_histpry', models.FloatField(default=0)),
                ('loan_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('property_area', models.CharField(choices=[('Urban', 'urban'), ('Rural', 'rural')], max_length=15)),
            ],
        ),
        migrations.DeleteModel(
            name='MLAlgorithm',
        ),
        migrations.DeleteModel(
            name='MLEndpoint',
        ),
    ]
