# Generated by Django 4.0.2 on 2022-05-02 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0004_approval_delete_approvals_remove_mlalgorithm_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='approval',
            name='age',
            field=models.IntegerField(default=0, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='firstname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='lastname',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='approval',
            name='married',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, null=True),
        ),
    ]
