# Generated by Django 4.0.4 on 2022-05-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_approval2'),
    ]

    operations = [
        migrations.RenameField(
            model_name='approval',
            old_name='ninety_days_late',
            new_name='amount_loan',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='open_credit_lines_and_loans',
            new_name='light_delinquencies',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='dependents',
            new_name='loan_ever_delinquent',
        ),
        migrations.RenameField(
            model_name='approval',
            old_name='real_estate_loans',
            new_name='serious_delinquencies',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='sixty_to_eighty_nine_days_late',
        ),
        migrations.RemoveField(
            model_name='approval',
            name='thirty_to_fifty_nine_days_late',
        ),
        migrations.AlterField(
            model_name='approval2',
            name='first_time_homebuyer',
            field=models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20),
        ),
        migrations.AlterField(
            model_name='approval2',
            name='occupancy_status',
            field=models.CharField(choices=[('Primary Residence', 'Primary Residence'), ('Secondary Residence', 'Secondary Residence'), ('Investment Property', 'Investment Property')], max_length=20),
        ),
    ]
