# Generated by Django 4.0.4 on 2022-06-01 13:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Approval',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, null=True)),
                ('monthly_income', models.FloatField()),
                ('monthly_debt', models.FloatField()),
                ('amount_loan', models.FloatField()),
                ('loan_ever_delinquent', models.IntegerField()),
                ('revolving_utilization', models.FloatField()),
                ('light_delinquencies', models.FloatField()),
                ('serious_delinquencies', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Approval2',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=15, null=True)),
                ('lastname', models.CharField(max_length=15, null=True)),
                ('age', models.IntegerField(null=True)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15, null=True)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15, null=True)),
                ('fico', models.FloatField()),
                ('first_time_homebuyer', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=20)),
                ('occupancy_status', models.CharField(choices=[('Primary Residence', 'Primary Residence'), ('Secondary Residence', 'Secondary Residence'), ('Investment Property', 'Investment Property')], max_length=20)),
                ('dti', models.FloatField()),
                ('upb', models.IntegerField()),
                ('ppm', models.CharField(max_length=20)),
                ('property_type', models.CharField(max_length=20)),
                ('loan_purpose', models.CharField(max_length=20)),
                ('original_loan_term', models.IntegerField()),
                ('number_of_borrowers', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='MLAlgorithm',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(default='Firstname', max_length=15)),
                ('lastname', models.CharField(default='Lastname', max_length=15)),
                ('gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=15)),
                ('married', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('dependents', models.IntegerField(default=0)),
                ('education', models.CharField(choices=[('Graduated', 'graduated'), ('Not_Graduate', 'not_graduated')], max_length=15)),
                ('self_employed', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('applicant_income', models.FloatField(default=0)),
                ('coapplicant_income', models.FloatField(default=0)),
                ('loan_amount', models.FloatField(default=0)),
                ('loan_amount_term', models.FloatField(default=0)),
                ('credit_histpry', models.FloatField(default=0)),
                ('loan_status', models.CharField(choices=[('Yes', 'Yes'), ('No', 'No')], max_length=15)),
                ('property_area', models.CharField(choices=[('Urban', 'Urban'), ('Rural', 'Rural')], max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='MLEndpoint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('owner', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='MLRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input_data', models.CharField(max_length=10000)),
                ('full_response', models.CharField(max_length=10000)),
                ('response', models.CharField(max_length=10000)),
                ('feedback', models.CharField(blank=True, max_length=10000, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_mlalgorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='products.mlalgorithm')),
            ],
        ),
        migrations.CreateModel(
            name='MLAlgorithmStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(max_length=128)),
                ('active', models.BooleanField()),
                ('created_by', models.CharField(max_length=128)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('parent_mlalgorithm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status', to='products.mlalgorithm')),
            ],
        ),
    ]
